CREATE TABLE hermes_data.cultures (
    id SERIAL PRIMARY KEY,
    name VARCHAR(1023) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hermes_data.units (
    id SERIAL PRIMARY KEY,
    division VARCHAR(1023) NOT NULL,
    pu VARCHAR(1023) NOT NULL,
    department VARCHAR(1023) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hermes_data.operations (
    id SERIAL PRIMARY KEY,
    name VARCHAR(1023) NOT NULL,
    note VARCHAR(1023) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
