version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: hermes # ваш логин
      POSTGRES_PASSWORD: password # ваш пароль
      POSTGRES_DB: hermes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hermes -d hermes"]
      interval: 1s
      timeout: 2s
    restart: unless-stopped

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: hermes # ваш логин
      MINIO_ROOT_PASSWORD: password # ваш пароль
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1s
      timeout: 2s
      retries: 5

  apollo:
    build:
      context: ./backend/apollo
    ports:
      - "8000:8000"
    volumes:
      - ./backend/apollo:/app
    networks:
      - app-network

  hermes:
    build:
      context: ./backend
      dockerfile: hermes/Dockerfile
    environment:
      DATABASE_URL: postgresql://hermes:password@postgres:5432/hermes?sslmode=disable # ваш логин и пароль
      APOLLO_IS_STUB: "false"
      FILTER_VERBIAGE: "true" # фильтр для отсеивания не нужных слов
    depends_on:
      postgres:
        condition: service_healthy
      apollo:
        condition: service_started
      minio:
        condition: service_healthy
    networks:
      - app-network

    restart: unless-stopped

  superset:
    build:
      context: ./backend/superset
    env_file:
      - ./backend/superset/.env
    ports:
      - "8088:8088"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - superset_home:/app/superset_home
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  apollo_data:
  superset_home:
  minio_data: