version: "3.9"

services:
  llm-structure-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-structure-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
